name = "QPSTools"
uuid = "91240044-bfa4-4bca-8577-4d123ebe80d7"
version = "0.1.0"
authors = ["Garrek Stemo <8449000+garrekstemo@users.noreply.github.com>"]

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
ElabFTW = "cc2949f1-737d-51f9-be66-fe7a219205ce"
JASCOFiles = "8f461479-960a-4355-a802-16cf8971498c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
SpectroscopyTools = "f1436f7a-66ba-4269-a153-8996db8f0853"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[sources]
ElabFTW = {url = "https://github.com/garrekstemo/ElabFTW.jl.git"}
JASCOFiles = {url = "https://github.com/garrekstemo/JASCOFiles.jl.git"}
SpectroscopyTools = {url = "https://github.com/garrekstemo/SpectroscopyTools.jl.git"}

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
